/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Age = number;
export type Email = string;
export type Phone = string;
export type Address = string;
export type JobType = "full_time" | "part_time" | "contract";
export type Profiles = Profile[];
export type Title = string;
export type Description = string | null;
export type Location = string | number;
export type Name2 = "Software Engineer";
export type Title1 = string;
export type Description1 = string | null;
export type Location1 = string | number;
export type Name3 = string;
export type Title2 = string;
export type Description2 = string | null;
export type Location2 = string | number;
export type Jobs = (ElectricalEngineer | SoftwareEngineer)[];

export interface AllModels {
  profile: Profile;
  profile_list: ProfileList;
  job: Job;
  software_engineer: SoftwareEngineer;
  electrical_engineer: ElectricalEngineer;
  job_list: JobList;
  [k: string]: unknown;
}
export interface Profile {
  name: Name;
  age: Age;
  email: Email;
  phone: Phone;
  address: Address;
  job_type: JobType;
  [k: string]: unknown;
}
export interface ProfileList {
  profiles: Profiles;
  [k: string]: unknown;
}
export interface Job {
  name: Name1;
  title: Title;
  description?: Description;
  location: Location;
  job_type: JobType;
  [k: string]: unknown;
}
export interface Name1 {
  [k: string]: unknown;
}
export interface SoftwareEngineer {
  name?: Name2;
  title: Title1;
  description?: Description1;
  location: Location1;
  job_type: JobType;
  [k: string]: unknown;
}
export interface ElectricalEngineer {
  name?: Name3;
  title: Title2;
  description?: Description2;
  location: Location2;
  job_type: JobType;
  [k: string]: unknown;
}
export interface JobList {
  jobs: Jobs;
  [k: string]: unknown;
}
