/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type Description = string | null;
export type Location = string | number;
export type JobType = "full_time" | "part_time" | "contract";

export interface Job {
  name: Name;
  title: Title;
  description?: Description;
  location: Location;
  job_type: JobType;
  [k: string]: unknown;
}
export interface Name {
  [k: string]: unknown;
}
