/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Title = string;
export type Description = string | null;
export type Location = string | number;
export type JobType = "full_time" | "part_time" | "contract";
export type Name1 = "Software Engineer";
export type Title1 = string;
export type Description1 = string | null;
export type Location1 = string | number;
export type Jobs = (ElectricalEngineer | SoftwareEngineer)[];

export interface JobList {
  jobs: Jobs;
  [k: string]: unknown;
}
export interface ElectricalEngineer {
  name?: Name;
  title: Title;
  description?: Description;
  location: Location;
  job_type: JobType;
  [k: string]: unknown;
}
export interface SoftwareEngineer {
  name?: Name1;
  title: Title1;
  description?: Description1;
  location: Location1;
  job_type: JobType;
  [k: string]: unknown;
}
