/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Age = number;
export type Email = string;
export type Phone = string;
export type Address = string;
export type JobType = "full_time" | "part_time" | "contract";
export type Profiles = Profile[];

export interface ProfileList {
  profiles: Profiles;
  [k: string]: unknown;
}
export interface Profile {
  name: Name;
  age: Age;
  email: Email;
  phone: Phone;
  address: Address;
  job_type: JobType;
  [k: string]: unknown;
}
