from convex_client.models import (
    RequestActionsGetSessionMetadata,
    RequestActionsRunTests,
    RequestActionsRunTestsArgs,
    RequestCodeSessionEventsCommitCodeSessionEvent,
    RequestCodeSessionEventsCommitCodeSessionEventArgs,
    RequestCodeSessionEventsCommitCodeSessionEventArgsEvent,
    RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2Data,
    RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3DataAfterInner,
    RequestSessionsEndSessionArgs,
    ResponseActionsGetSessionMetadataValue,
    ResponseActionsRunTestsValue,
    ResponseActionsRunTestsValueTestResultsInner,
    ResponseCodeSessionEventsGetLatestContentChangeEventValue,
    ResponseCodeSessionEventsGetLatestGroundTruthTestcaseExecutedEventValue,
    ResponseCodeSessionEventsGetLatestTestcaseChangeEventValue,
    ResponseCodeSessionEventsGetLatestUserTestcaseExecutedEventValue,
    ResponseCodeSessionStatesGetValue,
)

SessionMetadata = ResponseActionsGetSessionMetadataValue
CodeSessionState = ResponseCodeSessionStatesGetValue
CodeSessionContentChangedEvent = (
    ResponseCodeSessionEventsGetLatestContentChangeEventValue
)
CodeSessionTestcaseChangedEvent = (
    ResponseCodeSessionEventsGetLatestTestcaseChangeEventValue
)
CodeSessionUserTestcaseExecutedEvent = (
    ResponseCodeSessionEventsGetLatestUserTestcaseExecutedEventValue
)
CodeSessionGroundTruthTestcaseExecutedEvent = (
    ResponseCodeSessionEventsGetLatestGroundTruthTestcaseExecutedEventValue
)

RunTestsResult = ResponseActionsRunTestsValue
TestcaseResult = ResponseActionsRunTestsValueTestResultsInner
Testcase = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3DataAfterInner

RequestGetSessionMetadata = RequestActionsGetSessionMetadata
RequestGetSessionMetadataArgs = RequestSessionsEndSessionArgs

RequestTestCodeCorrectness = RequestActionsRunTests
RequestTestCodeCorrectnessArgs = RequestActionsRunTestsArgs

RequestCommitCodeSessionEvent = RequestCodeSessionEventsCommitCodeSessionEvent
RequestCommitCodeSessionEventArgs = RequestCodeSessionEventsCommitCodeSessionEventArgs

CodeSessionEvent = RequestCodeSessionEventsCommitCodeSessionEventArgsEvent
StageSwitchedEvent = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2Data
