from convex_client.models import (
    RequestActionsGetSessionMetadata,
    RequestActionsRunGroundTruthTest,
    RequestActionsRunGroundTruthTestArgs,
    RequestActionsRunTests,
    RequestActionsRunTestsArgs,
    RequestAgentStatesGetBySessionId,
    RequestAgentStatesSetBySessionId,
    RequestCodeSessionEventsCommitCodeSessionEvent,
    RequestCodeSessionEventsCommitCodeSessionEventArgs,
    RequestCodeSessionEventsCommitCodeSessionEventArgsEvent,
    RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2Data,
    RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3DataAfterInner,
    RequestSessionsEndSessionArgs,
    ResponseActionsGetSessionMetadataValue,
    ResponseActionsRunGroundTruthTestValueInner,
    ResponseActionsRunTestsValue,
    ResponseCodeSessionEventsGetLatestContentChangeEventValue,
    ResponseCodeSessionEventsGetLatestGroundTruthTestcaseExecutedEventValue,
    ResponseCodeSessionEventsGetLatestTestcaseChangeEventValue,
    ResponseCodeSessionEventsGetLatestUserTestcaseExecutedEventValue,
    ResponseCodeSessionStatesGetValue,
)

SessionMetadata = ResponseActionsGetSessionMetadataValue
CodeSessionState = ResponseCodeSessionStatesGetValue
CodeSessionContentChangedEvent = (
    ResponseCodeSessionEventsGetLatestContentChangeEventValue
)
CodeSessionTestcaseChangedEvent = (
    ResponseCodeSessionEventsGetLatestTestcaseChangeEventValue
)
CodeSessionUserTestcaseExecutedEvent = (
    ResponseCodeSessionEventsGetLatestUserTestcaseExecutedEventValue
)
CodeSessionGroundTruthTestcaseExecutedEvent = (
    ResponseCodeSessionEventsGetLatestGroundTruthTestcaseExecutedEventValue
)

RunTestsResult = ResponseActionsRunTestsValue
TestcaseResult = ResponseActionsRunGroundTruthTestValueInner
Testcase = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3DataAfterInner

RequestGetSessionMetadata = RequestActionsGetSessionMetadata
RequestGetSessionMetadataArgs = RequestSessionsEndSessionArgs

RequestTestCodeCorrectness = RequestActionsRunTests
RequestTestCodeCorrectnessArgs = RequestActionsRunTestsArgs

RequestCommitCodeSessionEvent = RequestCodeSessionEventsCommitCodeSessionEvent
RequestCommitCodeSessionEventArgs = RequestCodeSessionEventsCommitCodeSessionEventArgs

CodeSessionEvent = RequestCodeSessionEventsCommitCodeSessionEventArgsEvent
StageSwitchedEvent = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2Data

RequestTestCodeWithGroundTruth = RequestActionsRunGroundTruthTest
RequestTestCodeWithGroundTruthArgs = RequestActionsRunGroundTruthTestArgs
