# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_actions_get_session_metadata import ResponseActionsGetSessionMetadata

class TestResponseActionsGetSessionMetadata(unittest.TestCase):
    """ResponseActionsGetSessionMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseActionsGetSessionMetadata:
        """Test ResponseActionsGetSessionMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseActionsGetSessionMetadata`
        """
        model = ResponseActionsGetSessionMetadata()
        if include_optional:
            return ResponseActionsGetSessionMetadata(
                status = 'success',
                error_message = '',
                error_data = None,
                value = convex_client.models.response_actions_get_session_metadata_value.Response_actions_getSessionMetadata_value(
                    agent_thread_id = '', 
                    assistant_id = '', 
                    question_content = '', 
                    question_title = '', 
                    session_id = '', 
                    session_status = '', )
            )
        else:
            return ResponseActionsGetSessionMetadata(
                status = 'success',
        )
        """

    def testResponseActionsGetSessionMetadata(self):
        """Test ResponseActionsGetSessionMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
