# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_code_session_states_get_value_testcases_inner import ResponseCodeSessionStatesGetValueTestcasesInner

class TestResponseCodeSessionStatesGetValueTestcasesInner(unittest.TestCase):
    """ResponseCodeSessionStatesGetValueTestcasesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseCodeSessionStatesGetValueTestcasesInner:
        """Test ResponseCodeSessionStatesGetValueTestcasesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseCodeSessionStatesGetValueTestcasesInner`
        """
        model = ResponseCodeSessionStatesGetValueTestcasesInner()
        if include_optional:
            return ResponseCodeSessionStatesGetValueTestcasesInner(
                expected_output = None,
                input = convex_client.models.input.input()
            )
        else:
            return ResponseCodeSessionStatesGetValueTestcasesInner(
                input = convex_client.models.input.input(),
        )
        """

    def testResponseCodeSessionStatesGetValueTestcasesInner(self):
        """Test ResponseCodeSessionStatesGetValueTestcasesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
