# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_coding_question_set_get_study_plan_by_name import ResponseCodingQuestionSetGetStudyPlanByName

class TestResponseCodingQuestionSetGetStudyPlanByName(unittest.TestCase):
    """ResponseCodingQuestionSetGetStudyPlanByName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseCodingQuestionSetGetStudyPlanByName:
        """Test ResponseCodingQuestionSetGetStudyPlanByName
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseCodingQuestionSetGetStudyPlanByName`
        """
        model = ResponseCodingQuestionSetGetStudyPlanByName()
        if include_optional:
            return ResponseCodingQuestionSetGetStudyPlanByName(
                status = 'success',
                error_message = '',
                error_data = None,
                value = None
            )
        else:
            return ResponseCodingQuestionSetGetStudyPlanByName(
                status = 'success',
        )
        """

    def testResponseCodingQuestionSetGetStudyPlanByName(self):
        """Test ResponseCodingQuestionSetGetStudyPlanByName"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
