# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_actions_generate_question import RequestActionsGenerateQuestion

class TestRequestActionsGenerateQuestion(unittest.TestCase):
    """RequestActionsGenerateQuestion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestActionsGenerateQuestion:
        """Test RequestActionsGenerateQuestion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestActionsGenerateQuestion`
        """
        model = RequestActionsGenerateQuestion()
        if include_optional:
            return RequestActionsGenerateQuestion(
                args = convex_client.models.request_actions_generate_question_args.Request_actions_generateQuestion_args(
                    question_content = '', 
                    question_title = '', )
            )
        else:
            return RequestActionsGenerateQuestion(
                args = convex_client.models.request_actions_generate_question_args.Request_actions_generateQuestion_args(
                    question_content = '', 
                    question_title = '', ),
        )
        """

    def testRequestActionsGenerateQuestion(self):
        """Test RequestActionsGenerateQuestion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
