# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_invite_codes_create_invite_code import RequestInviteCodesCreateInviteCode

class TestRequestInviteCodesCreateInviteCode(unittest.TestCase):
    """RequestInviteCodesCreateInviteCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestInviteCodesCreateInviteCode:
        """Test RequestInviteCodesCreateInviteCode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestInviteCodesCreateInviteCode`
        """
        model = RequestInviteCodesCreateInviteCode()
        if include_optional:
            return RequestInviteCodesCreateInviteCode(
                args = convex_client.models.request_invite_codes_create_invite_code_args.Request_inviteCodes_createInviteCode_args(
                    assigned_role = null, )
            )
        else:
            return RequestInviteCodesCreateInviteCode(
                args = convex_client.models.request_invite_codes_create_invite_code_args.Request_inviteCodes_createInviteCode_args(
                    assigned_role = null, ),
        )
        """

    def testRequestInviteCodesCreateInviteCode(self):
        """Test RequestInviteCodesCreateInviteCode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
