# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.api.query_api import QueryApi


class TestQueryApi(unittest.TestCase):
    """QueryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QueryApi()

    def tearDown(self) -> None:
        pass

    def test_api_run_code_session_events_get_next_event_batch_post(self) -> None:
        """Test case for api_run_code_session_events_get_next_event_batch_post

        Calls a query at the path codeSessionEvents.js:getNextEventBatch
        """
        pass

    def test_api_run_code_session_states_get_editor_state_post(self) -> None:
        """Test case for api_run_code_session_states_get_editor_state_post

        Calls a query at the path codeSessionStates.js:getEditorState
        """
        pass

    def test_api_run_code_session_states_get_post(self) -> None:
        """Test case for api_run_code_session_states_get_post

        Calls a query at the path codeSessionStates.js:get
        """
        pass

    def test_api_run_code_session_states_get_session_state_by_session_id_post(self) -> None:
        """Test case for api_run_code_session_states_get_session_state_by_session_id_post

        Calls a query at the path codeSessionStates.js:getSessionStateBySessionId
        """
        pass

    def test_api_run_code_session_states_get_terminal_state_post(self) -> None:
        """Test case for api_run_code_session_states_get_terminal_state_post

        Calls a query at the path codeSessionStates.js:getTerminalState
        """
        pass

    def test_api_run_questions_get_all_post(self) -> None:
        """Test case for api_run_questions_get_all_post

        Calls a query at the path questions.js:getAll
        """
        pass

    def test_api_run_questions_get_by_id_post(self) -> None:
        """Test case for api_run_questions_get_by_id_post

        Calls a query at the path questions.js:getById
        """
        pass

    def test_api_run_sessions_exists_post(self) -> None:
        """Test case for api_run_sessions_exists_post

        Calls a query at the path sessions.js:exists
        """
        pass

    def test_api_run_sessions_get_active_session_post(self) -> None:
        """Test case for api_run_sessions_get_active_session_post

        Calls a query at the path sessions.js:getActiveSession
        """
        pass

    def test_api_run_sessions_get_by_id_post(self) -> None:
        """Test case for api_run_sessions_get_by_id_post

        Calls a query at the path sessions.js:getById
        """
        pass

    def test_api_run_sessions_get_by_user_id_post(self) -> None:
        """Test case for api_run_sessions_get_by_user_id_post

        Calls a query at the path sessions.js:getByUserId
        """
        pass

    def test_api_run_user_profiles_get_user_profile_post(self) -> None:
        """Test case for api_run_user_profiles_get_user_profile_post

        Calls a query at the path userProfiles.js:getUserProfile
        """
        pass


if __name__ == '__main__':
    unittest.main()
