# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_code_session_events_get_latest_ground_truth_testcase_executed_event_value import ResponseCodeSessionEventsGetLatestGroundTruthTestcaseExecutedEventValue

class TestResponseCodeSessionEventsGetLatestGroundTruthTestcaseExecutedEventValue(unittest.TestCase):
    """ResponseCodeSessionEventsGetLatestGroundTruthTestcaseExecutedEventValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseCodeSessionEventsGetLatestGroundTruthTestcaseExecutedEventValue:
        """Test ResponseCodeSessionEventsGetLatestGroundTruthTestcaseExecutedEventValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseCodeSessionEventsGetLatestGroundTruthTestcaseExecutedEventValue`
        """
        model = ResponseCodeSessionEventsGetLatestGroundTruthTestcaseExecutedEventValue()
        if include_optional:
            return ResponseCodeSessionEventsGetLatestGroundTruthTestcaseExecutedEventValue(
                event = convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_7.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_7(
                    data = convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_6_data.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_6_data(
                        test_results = [
                            convex_client.models.response_actions_run_tests_value_test_results_inner.Response_actions_runTests_value_testResults_inner(
                                actual = null, 
                                case_number = 1.337, 
                                error = '', 
                                expected = null, 
                                input = convex_client.models.input.input(), 
                                passed = True, 
                                stdout = '', )
                            ], ), 
                    type = 'groundtruth_testcase_executed', ),
                id = '',
                ts = 1.337
            )
        else:
            return ResponseCodeSessionEventsGetLatestGroundTruthTestcaseExecutedEventValue(
                event = convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_7.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_7(
                    data = convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_6_data.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_6_data(
                        test_results = [
                            convex_client.models.response_actions_run_tests_value_test_results_inner.Response_actions_runTests_value_testResults_inner(
                                actual = null, 
                                case_number = 1.337, 
                                error = '', 
                                expected = null, 
                                input = convex_client.models.input.input(), 
                                passed = True, 
                                stdout = '', )
                            ], ), 
                    type = 'groundtruth_testcase_executed', ),
                id = '',
                ts = 1.337,
        )
        """

    def testResponseCodeSessionEventsGetLatestGroundTruthTestcaseExecutedEventValue(self):
        """Test ResponseCodeSessionEventsGetLatestGroundTruthTestcaseExecutedEventValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
