# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of5_data import RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5Data

class TestRequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5Data(unittest.TestCase):
    """RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5Data:
        """Test RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5Data
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5Data`
        """
        model = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5Data()
        if include_optional:
            return RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5Data(
                after = [
                    convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_5_data_after_inner.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_5_data_after_inner(
                        expected_output = null, 
                        input = convex_client.models.input.input(), )
                    ],
                before = [
                    convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_5_data_after_inner.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_5_data_after_inner(
                        expected_output = null, 
                        input = convex_client.models.input.input(), )
                    ]
            )
        else:
            return RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5Data(
                after = [
                    convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_5_data_after_inner.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_5_data_after_inner(
                        expected_output = null, 
                        input = convex_client.models.input.input(), )
                    ],
                before = [
                    convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_5_data_after_inner.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_5_data_after_inner(
                        expected_output = null, 
                        input = convex_client.models.input.input(), )
                    ],
        )
        """

    def testRequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5Data(self):
        """Test RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5Data"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
