# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_admins_patch_user_subscription import RequestAdminsPatchUserSubscription

class TestRequestAdminsPatchUserSubscription(unittest.TestCase):
    """RequestAdminsPatchUserSubscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestAdminsPatchUserSubscription:
        """Test RequestAdminsPatchUserSubscription
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestAdminsPatchUserSubscription`
        """
        model = RequestAdminsPatchUserSubscription()
        if include_optional:
            return RequestAdminsPatchUserSubscription(
                args = convex_client.models.request_admins_patch_user_subscription_args.Request_admins_patchUserSubscription_args(
                    minutes_remaining = 1.337, 
                    subscription = null, 
                    user_id = '', )
            )
        else:
            return RequestAdminsPatchUserSubscription(
                args = convex_client.models.request_admins_patch_user_subscription_args.Request_admins_patchUserSubscription_args(
                    minutes_remaining = 1.337, 
                    subscription = null, 
                    user_id = '', ),
        )
        """

    def testRequestAdminsPatchUserSubscription(self):
        """Test RequestAdminsPatchUserSubscription"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
