# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_actions_get_editor_snapshot_value_terminal import ResponseActionsGetEditorSnapshotValueTerminal

class TestResponseActionsGetEditorSnapshotValueTerminal(unittest.TestCase):
    """ResponseActionsGetEditorSnapshotValueTerminal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseActionsGetEditorSnapshotValueTerminal:
        """Test ResponseActionsGetEditorSnapshotValueTerminal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseActionsGetEditorSnapshotValueTerminal`
        """
        model = ResponseActionsGetEditorSnapshotValueTerminal()
        if include_optional:
            return ResponseActionsGetEditorSnapshotValueTerminal(
                execution_time = 1.337,
                is_error = True,
                output = ''
            )
        else:
            return ResponseActionsGetEditorSnapshotValueTerminal(
                is_error = True,
                output = '',
        )
        """

    def testResponseActionsGetEditorSnapshotValueTerminal(self):
        """Test ResponseActionsGetEditorSnapshotValueTerminal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
