# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_actions_get_editor_snapshot_value import ResponseActionsGetEditorSnapshotValue

class TestResponseActionsGetEditorSnapshotValue(unittest.TestCase):
    """ResponseActionsGetEditorSnapshotValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseActionsGetEditorSnapshotValue:
        """Test ResponseActionsGetEditorSnapshotValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseActionsGetEditorSnapshotValue`
        """
        model = ResponseActionsGetEditorSnapshotValue()
        if include_optional:
            return ResponseActionsGetEditorSnapshotValue(
                editor = convex_client.models.response_actions_get_editor_snapshot_value_editor.Response_actions_getEditorSnapshot_value_editor(
                    content = '', 
                    language = '', 
                    last_updated = 1.337, ),
                session_id = '',
                terminal = convex_client.models.request_editor_snapshots_create_args_terminal.Request_editorSnapshots_create_args_terminal(
                    execution_time = 1.337, 
                    is_error = True, 
                    output = '', )
            )
        else:
            return ResponseActionsGetEditorSnapshotValue(
                editor = convex_client.models.response_actions_get_editor_snapshot_value_editor.Response_actions_getEditorSnapshot_value_editor(
                    content = '', 
                    language = '', 
                    last_updated = 1.337, ),
                session_id = '',
                terminal = convex_client.models.request_editor_snapshots_create_args_terminal.Request_editorSnapshots_create_args_terminal(
                    execution_time = 1.337, 
                    is_error = True, 
                    output = '', ),
        )
        """

    def testResponseActionsGetEditorSnapshotValue(self):
        """Test ResponseActionsGetEditorSnapshotValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
