# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_pricings_get_pricings_internal import RequestPricingsGetPricingsInternal

class TestRequestPricingsGetPricingsInternal(unittest.TestCase):
    """RequestPricingsGetPricingsInternal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestPricingsGetPricingsInternal:
        """Test RequestPricingsGetPricingsInternal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestPricingsGetPricingsInternal`
        """
        model = RequestPricingsGetPricingsInternal()
        if include_optional:
            return RequestPricingsGetPricingsInternal(
                args = convex_client.models.request_pricings_get_pricing_args.Request_pricings_getPricing_args(
                    tier = null, )
            )
        else:
            return RequestPricingsGetPricingsInternal(
                args = convex_client.models.request_pricings_get_pricing_args.Request_pricings_getPricing_args(
                    tier = null, ),
        )
        """

    def testRequestPricingsGetPricingsInternal(self):
        """Test RequestPricingsGetPricingsInternal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
