# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of3 import RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3

class TestRequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3(unittest.TestCase):
    """RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3:
        """Test RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3`
        """
        model = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3()
        if include_optional:
            return RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3(
                data = None,
                type = 'testcase_removed'
            )
        else:
            return RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3(
                data = None,
                type = 'testcase_removed',
        )
        """

    def testRequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3(self):
        """Test RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
