# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_sessions_get_by_id_internal import RequestSessionsGetByIdInternal

class TestRequestSessionsGetByIdInternal(unittest.TestCase):
    """RequestSessionsGetByIdInternal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestSessionsGetByIdInternal:
        """Test RequestSessionsGetByIdInternal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestSessionsGetByIdInternal`
        """
        model = RequestSessionsGetByIdInternal()
        if include_optional:
            return RequestSessionsGetByIdInternal(
                args = convex_client.models.request_sessions_end_session_args.Request_sessions_endSession_args(
                    session_id = '', )
            )
        else:
            return RequestSessionsGetByIdInternal(
                args = convex_client.models.request_sessions_end_session_args.Request_sessions_endSession_args(
                    session_id = '', ),
        )
        """

    def testRequestSessionsGetByIdInternal(self):
        """Test RequestSessionsGetByIdInternal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
