# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_coding_question_set_get_coding_question_sets_args import RequestCodingQuestionSetGetCodingQuestionSetsArgs

class TestRequestCodingQuestionSetGetCodingQuestionSetsArgs(unittest.TestCase):
    """RequestCodingQuestionSetGetCodingQuestionSetsArgs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCodingQuestionSetGetCodingQuestionSetsArgs:
        """Test RequestCodingQuestionSetGetCodingQuestionSetsArgs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCodingQuestionSetGetCodingQuestionSetsArgs`
        """
        model = RequestCodingQuestionSetGetCodingQuestionSetsArgs()
        if include_optional:
            return RequestCodingQuestionSetGetCodingQuestionSetsArgs(
                name = ''
            )
        else:
            return RequestCodingQuestionSetGetCodingQuestionSetsArgs(
                name = '',
        )
        """

    def testRequestCodingQuestionSetGetCodingQuestionSetsArgs(self):
        """Test RequestCodingQuestionSetGetCodingQuestionSetsArgs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
