# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_user_profiles_decrement_minutes_remaining_args import RequestUserProfilesDecrementMinutesRemainingArgs

class TestRequestUserProfilesDecrementMinutesRemainingArgs(unittest.TestCase):
    """RequestUserProfilesDecrementMinutesRemainingArgs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestUserProfilesDecrementMinutesRemainingArgs:
        """Test RequestUserProfilesDecrementMinutesRemainingArgs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestUserProfilesDecrementMinutesRemainingArgs`
        """
        model = RequestUserProfilesDecrementMinutesRemainingArgs()
        if include_optional:
            return RequestUserProfilesDecrementMinutesRemainingArgs(
                minutes = 1.337
            )
        else:
            return RequestUserProfilesDecrementMinutesRemainingArgs(
                minutes = 1.337,
        )
        """

    def testRequestUserProfilesDecrementMinutesRemainingArgs(self):
        """Test RequestUserProfilesDecrementMinutesRemainingArgs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
