# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_code_session_events_get_next_event_batch import RequestCodeSessionEventsGetNextEventBatch

class TestRequestCodeSessionEventsGetNextEventBatch(unittest.TestCase):
    """RequestCodeSessionEventsGetNextEventBatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCodeSessionEventsGetNextEventBatch:
        """Test RequestCodeSessionEventsGetNextEventBatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCodeSessionEventsGetNextEventBatch`
        """
        model = RequestCodeSessionEventsGetNextEventBatch()
        if include_optional:
            return RequestCodeSessionEventsGetNextEventBatch(
                args = convex_client.models.request_code_session_events_get_next_event_batch_args.Request_codeSessionEvents_getNextEventBatch_args(
                    code_session_state_id = '', 
                    limit = 1.337, )
            )
        else:
            return RequestCodeSessionEventsGetNextEventBatch(
                args = convex_client.models.request_code_session_events_get_next_event_batch_args.Request_codeSessionEvents_getNextEventBatch_args(
                    code_session_state_id = '', 
                    limit = 1.337, ),
        )
        """

    def testRequestCodeSessionEventsGetNextEventBatch(self):
        """Test RequestCodeSessionEventsGetNextEventBatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
