# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_jobs_create import RequestJobsCreate

class TestRequestJobsCreate(unittest.TestCase):
    """RequestJobsCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestJobsCreate:
        """Test RequestJobsCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestJobsCreate`
        """
        model = RequestJobsCreate()
        if include_optional:
            return RequestJobsCreate(
                args = convex_client.models.request_jobs_create_args.Request_jobs_create_args(
                    last_update = 1.337, 
                    num_retries = 1.337, 
                    session_id = '', 
                    status = null, )
            )
        else:
            return RequestJobsCreate(
                args = convex_client.models.request_jobs_create_args.Request_jobs_create_args(
                    last_update = 1.337, 
                    num_retries = 1.337, 
                    session_id = '', 
                    status = null, ),
        )
        """

    def testRequestJobsCreate(self):
        """Test RequestJobsCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
