# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_code_session_events_get_next_event_batch_value_inner import ResponseCodeSessionEventsGetNextEventBatchValueInner

class TestResponseCodeSessionEventsGetNextEventBatchValueInner(unittest.TestCase):
    """ResponseCodeSessionEventsGetNextEventBatchValueInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseCodeSessionEventsGetNextEventBatchValueInner:
        """Test ResponseCodeSessionEventsGetNextEventBatchValueInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseCodeSessionEventsGetNextEventBatchValueInner`
        """
        model = ResponseCodeSessionEventsGetNextEventBatchValueInner()
        if include_optional:
            return ResponseCodeSessionEventsGetNextEventBatchValueInner(
                event = None,
                ts = 1.337
            )
        else:
            return ResponseCodeSessionEventsGetNextEventBatchValueInner(
                event = None,
                ts = 1.337,
        )
        """

    def testResponseCodeSessionEventsGetNextEventBatchValueInner(self):
        """Test ResponseCodeSessionEventsGetNextEventBatchValueInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
