# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of5 import RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5

class TestRequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5(unittest.TestCase):
    """RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5:
        """Test RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5`
        """
        model = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5()
        if include_optional:
            return RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5(
                data = None,
                type = 'testcase_changed'
            )
        else:
            return RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5(
                data = None,
                type = 'testcase_changed',
        )
        """

    def testRequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5(self):
        """Test RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
