# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_code_session_states_get import ResponseCodeSessionStatesGet

class TestResponseCodeSessionStatesGet(unittest.TestCase):
    """ResponseCodeSessionStatesGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseCodeSessionStatesGet:
        """Test ResponseCodeSessionStatesGet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseCodeSessionStatesGet`
        """
        model = ResponseCodeSessionStatesGet()
        if include_optional:
            return ResponseCodeSessionStatesGet(
                status = 'success',
                error_message = '',
                error_data = None,
                value = convex_client.models.response_code_session_states_get_value.Response_codeSessionStates_get_value(
                    _creation_time = 1.337, 
                    _id = '', 
                    display_question = True, 
                    editor = convex_client.models.response_code_session_states_get_value_editor.Response_codeSessionStates_get_value_editor(
                        content = '', 
                        language = '', 
                        last_updated = 1.337, ), 
                    session_id = '', 
                    terminal = convex_client.models.response_code_session_states_get_value_terminal.Response_codeSessionStates_get_value_terminal(
                        execution_time = 1.337, 
                        is_error = True, 
                        output = '', ), 
                    testcases = [
                        convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_5_data_after_inner.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_5_data_after_inner(
                            expected_output = null, 
                            input = convex_client.models.input.input(), )
                        ], )
            )
        else:
            return ResponseCodeSessionStatesGet(
                status = 'success',
        )
        """

    def testResponseCodeSessionStatesGet(self):
        """Test ResponseCodeSessionStatesGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
