# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.api.mutation_api import MutationApi


class TestMutationApi(unittest.TestCase):
    """MutationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MutationApi()

    def tearDown(self) -> None:
        pass

    def test_api_run_admins_create_user_profile_post(self) -> None:
        """Test case for api_run_admins_create_user_profile_post

        Calls a mutation at the path admins.js:createUserProfile
        """
        pass

    def test_api_run_admins_patch_user_subscription_post(self) -> None:
        """Test case for api_run_admins_patch_user_subscription_post

        Calls a mutation at the path admins.js:patchUserSubscription
        """
        pass

    def test_api_run_code_session_events_ack_code_session_event_post(self) -> None:
        """Test case for api_run_code_session_events_ack_code_session_event_post

        Calls a mutation at the path codeSessionEvents.js:ackCodeSessionEvent
        """
        pass

    def test_api_run_code_session_events_commit_code_session_event_post(self) -> None:
        """Test case for api_run_code_session_events_commit_code_session_event_post

        Calls a mutation at the path codeSessionEvents.js:commitCodeSessionEvent
        """
        pass

    def test_api_run_invite_codes_apply_invite_code_post(self) -> None:
        """Test case for api_run_invite_codes_apply_invite_code_post

        Calls a mutation at the path inviteCodes.js:applyInviteCode
        """
        pass

    def test_api_run_sessions_create_code_session_post(self) -> None:
        """Test case for api_run_sessions_create_code_session_post

        Calls a mutation at the path sessions.js:createCodeSession
        """
        pass

    def test_api_run_sessions_end_session_post(self) -> None:
        """Test case for api_run_sessions_end_session_post

        Calls a mutation at the path sessions.js:endSession
        """
        pass

    def test_api_run_sessions_start_session_post(self) -> None:
        """Test case for api_run_sessions_start_session_post

        Calls a mutation at the path sessions.js:startSession
        """
        pass


if __name__ == '__main__':
    unittest.main()
