# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_code_session_states_get_value import ResponseCodeSessionStatesGetValue

class TestResponseCodeSessionStatesGetValue(unittest.TestCase):
    """ResponseCodeSessionStatesGetValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseCodeSessionStatesGetValue:
        """Test ResponseCodeSessionStatesGetValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseCodeSessionStatesGetValue`
        """
        model = ResponseCodeSessionStatesGetValue()
        if include_optional:
            return ResponseCodeSessionStatesGetValue(
                creation_time = 1.337,
                id = '',
                current_stage_idx = 1.337,
                editor = convex_client.models.response_code_session_states_get_value_editor.Response_codeSessionStates_get_value_editor(
                    content = '', 
                    language = '', 
                    last_updated = 1.337, ),
                session_id = '',
                terminal = convex_client.models.response_code_session_states_get_value_terminal.Response_codeSessionStates_get_value_terminal(
                    execution_time = 1.337, 
                    is_error = True, 
                    output = '', ),
                testcases = [
                    convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_3_data_after_inner.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_3_data_after_inner(
                        expected_output = null, 
                        input = convex_client.models.input.input(), )
                    ],
                transition_timestamps = [
                    1.337
                    ]
            )
        else:
            return ResponseCodeSessionStatesGetValue(
                creation_time = 1.337,
                id = '',
                current_stage_idx = 1.337,
                editor = convex_client.models.response_code_session_states_get_value_editor.Response_codeSessionStates_get_value_editor(
                    content = '', 
                    language = '', 
                    last_updated = 1.337, ),
                session_id = '',
                terminal = convex_client.models.response_code_session_states_get_value_terminal.Response_codeSessionStates_get_value_terminal(
                    execution_time = 1.337, 
                    is_error = True, 
                    output = '', ),
                testcases = [
                    convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_3_data_after_inner.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_3_data_after_inner(
                        expected_output = null, 
                        input = convex_client.models.input.input(), )
                    ],
                transition_timestamps = [
                    1.337
                    ],
        )
        """

    def testResponseCodeSessionStatesGetValue(self):
        """Test ResponseCodeSessionStatesGetValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
