# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_code_session_events_commit_code_session_event_args_event import RequestCodeSessionEventsCommitCodeSessionEventArgsEvent

class TestRequestCodeSessionEventsCommitCodeSessionEventArgsEvent(unittest.TestCase):
    """RequestCodeSessionEventsCommitCodeSessionEventArgsEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCodeSessionEventsCommitCodeSessionEventArgsEvent:
        """Test RequestCodeSessionEventsCommitCodeSessionEventArgsEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCodeSessionEventsCommitCodeSessionEventArgsEvent`
        """
        model = RequestCodeSessionEventsCommitCodeSessionEventArgsEvent()
        if include_optional:
            return RequestCodeSessionEventsCommitCodeSessionEventArgsEvent(
                data = convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_2_data.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_2_data(
                    stage = '', ),
                type = 'content_changed'
            )
        else:
            return RequestCodeSessionEventsCommitCodeSessionEventArgsEvent(
                data = convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_2_data.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_2_data(
                    stage = '', ),
                type = 'content_changed',
        )
        """

    def testRequestCodeSessionEventsCommitCodeSessionEventArgsEvent(self):
        """Test RequestCodeSessionEventsCommitCodeSessionEventArgsEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
