# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_code_session_states_get_latest_snapshot_by_session_id import RequestCodeSessionStatesGetLatestSnapshotBySessionId

class TestRequestCodeSessionStatesGetLatestSnapshotBySessionId(unittest.TestCase):
    """RequestCodeSessionStatesGetLatestSnapshotBySessionId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCodeSessionStatesGetLatestSnapshotBySessionId:
        """Test RequestCodeSessionStatesGetLatestSnapshotBySessionId
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCodeSessionStatesGetLatestSnapshotBySessionId`
        """
        model = RequestCodeSessionStatesGetLatestSnapshotBySessionId()
        if include_optional:
            return RequestCodeSessionStatesGetLatestSnapshotBySessionId(
                args = convex_client.models.request_sessions_end_session_args.Request_sessions_endSession_args(
                    session_id = '', )
            )
        else:
            return RequestCodeSessionStatesGetLatestSnapshotBySessionId(
                args = convex_client.models.request_sessions_end_session_args.Request_sessions_endSession_args(
                    session_id = '', ),
        )
        """

    def testRequestCodeSessionStatesGetLatestSnapshotBySessionId(self):
        """Test RequestCodeSessionStatesGetLatestSnapshotBySessionId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
