# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_editor_snapshots_create import RequestEditorSnapshotsCreate

class TestRequestEditorSnapshotsCreate(unittest.TestCase):
    """RequestEditorSnapshotsCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestEditorSnapshotsCreate:
        """Test RequestEditorSnapshotsCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestEditorSnapshotsCreate`
        """
        model = RequestEditorSnapshotsCreate()
        if include_optional:
            return RequestEditorSnapshotsCreate(
                args = convex_client.models.request_editor_snapshots_create_args.Request_editorSnapshots_create_args(
                    editor = convex_client.models.request_editor_snapshots_create_args_editor.Request_editorSnapshots_create_args_editor(
                        content = '', 
                        function_name = '', 
                        input_parameters = [
                            ''
                            ], 
                        language = '', 
                        last_updated = 1.337, ), 
                    session_id = '', 
                    terminal = convex_client.models.request_editor_snapshots_create_args_terminal.Request_editorSnapshots_create_args_terminal(
                        execution_time = 1.337, 
                        is_error = True, 
                        output = '', ), )
            )
        else:
            return RequestEditorSnapshotsCreate(
                args = convex_client.models.request_editor_snapshots_create_args.Request_editorSnapshots_create_args(
                    editor = convex_client.models.request_editor_snapshots_create_args_editor.Request_editorSnapshots_create_args_editor(
                        content = '', 
                        function_name = '', 
                        input_parameters = [
                            ''
                            ], 
                        language = '', 
                        last_updated = 1.337, ), 
                    session_id = '', 
                    terminal = convex_client.models.request_editor_snapshots_create_args_terminal.Request_editorSnapshots_create_args_terminal(
                        execution_time = 1.337, 
                        is_error = True, 
                        output = '', ), ),
        )
        """

    def testRequestEditorSnapshotsCreate(self):
        """Test RequestEditorSnapshotsCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
