# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of3_data_after_inner import RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3DataAfterInner

class TestRequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3DataAfterInner(unittest.TestCase):
    """RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3DataAfterInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3DataAfterInner:
        """Test RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3DataAfterInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3DataAfterInner`
        """
        model = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3DataAfterInner()
        if include_optional:
            return RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3DataAfterInner(
                expected_output = None,
                input = convex_client.models.input.input()
            )
        else:
            return RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3DataAfterInner(
                input = convex_client.models.input.input(),
        )
        """

    def testRequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3DataAfterInner(self):
        """Test RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3DataAfterInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
