# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_code_session_events_get_latest_testcase_change_event_value import ResponseCodeSessionEventsGetLatestTestcaseChangeEventValue

class TestResponseCodeSessionEventsGetLatestTestcaseChangeEventValue(unittest.TestCase):
    """ResponseCodeSessionEventsGetLatestTestcaseChangeEventValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseCodeSessionEventsGetLatestTestcaseChangeEventValue:
        """Test ResponseCodeSessionEventsGetLatestTestcaseChangeEventValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseCodeSessionEventsGetLatestTestcaseChangeEventValue`
        """
        model = ResponseCodeSessionEventsGetLatestTestcaseChangeEventValue()
        if include_optional:
            return ResponseCodeSessionEventsGetLatestTestcaseChangeEventValue(
                event = convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_5.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_5(
                    data = convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_5_data.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_5_data(
                        after = [
                            convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_5_data_after_inner.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_5_data_after_inner(
                                expected_output = null, 
                                input = convex_client.models.input.input(), )
                            ], 
                        before = [
                            convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_5_data_after_inner.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_5_data_after_inner(
                                expected_output = null, 
                                input = convex_client.models.input.input(), )
                            ], ), 
                    type = 'testcase_changed', ),
                id = '',
                ts = 1.337
            )
        else:
            return ResponseCodeSessionEventsGetLatestTestcaseChangeEventValue(
                event = convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_5.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_5(
                    data = convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_5_data.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_5_data(
                        after = [
                            convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_5_data_after_inner.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_5_data_after_inner(
                                expected_output = null, 
                                input = convex_client.models.input.input(), )
                            ], 
                        before = [
                            convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of_5_data_after_inner.Request_codeSessionEvents_commitCodeSessionEvent_args_event_oneOf_5_data_after_inner(
                                expected_output = null, 
                                input = convex_client.models.input.input(), )
                            ], ), 
                    type = 'testcase_changed', ),
                id = '',
                ts = 1.337,
        )
        """

    def testResponseCodeSessionEventsGetLatestTestcaseChangeEventValue(self):
        """Test ResponseCodeSessionEventsGetLatestTestcaseChangeEventValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
