# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_code_session_events_get_next_content_change_event_args import RequestCodeSessionEventsGetNextContentChangeEventArgs

class TestRequestCodeSessionEventsGetNextContentChangeEventArgs(unittest.TestCase):
    """RequestCodeSessionEventsGetNextContentChangeEventArgs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCodeSessionEventsGetNextContentChangeEventArgs:
        """Test RequestCodeSessionEventsGetNextContentChangeEventArgs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCodeSessionEventsGetNextContentChangeEventArgs`
        """
        model = RequestCodeSessionEventsGetNextContentChangeEventArgs()
        if include_optional:
            return RequestCodeSessionEventsGetNextContentChangeEventArgs(
                code_session_state_id = ''
            )
        else:
            return RequestCodeSessionEventsGetNextContentChangeEventArgs(
                code_session_state_id = '',
        )
        """

    def testRequestCodeSessionEventsGetNextContentChangeEventArgs(self):
        """Test RequestCodeSessionEventsGetNextContentChangeEventArgs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
