# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of6_data import RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf6Data

class TestRequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf6Data(unittest.TestCase):
    """RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf6Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf6Data:
        """Test RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf6Data
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf6Data`
        """
        model = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf6Data()
        if include_optional:
            return RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf6Data(
                test_results = [
                    convex_client.models.response_actions_run_tests_value_test_results_inner.Response_actions_runTests_value_testResults_inner(
                        actual = null, 
                        case_number = 1.337, 
                        error = '', 
                        expected = null, 
                        input = convex_client.models.input.input(), 
                        passed = True, 
                        stdout = '', )
                    ]
            )
        else:
            return RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf6Data(
                test_results = [
                    convex_client.models.response_actions_run_tests_value_test_results_inner.Response_actions_runTests_value_testResults_inner(
                        actual = null, 
                        case_number = 1.337, 
                        error = '', 
                        expected = null, 
                        input = convex_client.models.input.input(), 
                        passed = True, 
                        stdout = '', )
                    ],
        )
        """

    def testRequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf6Data(self):
        """Test RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf6Data"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
