# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_agent_states_get_by_session_id import ResponseAgentStatesGetBySessionId

class TestResponseAgentStatesGetBySessionId(unittest.TestCase):
    """ResponseAgentStatesGetBySessionId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseAgentStatesGetBySessionId:
        """Test ResponseAgentStatesGetBySessionId
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseAgentStatesGetBySessionId`
        """
        model = ResponseAgentStatesGetBySessionId()
        if include_optional:
            return ResponseAgentStatesGetBySessionId(
                status = 'success',
                error_message = '',
                error_data = None,
                value = convex_client.models.response_agent_states_get_by_session_id_value.Response_agentStates_getBySessionId_value(
                    last_updated = 1.337, 
                    state = null, )
            )
        else:
            return ResponseAgentStatesGetBySessionId(
                status = 'success',
        )
        """

    def testResponseAgentStatesGetBySessionId(self):
        """Test ResponseAgentStatesGetBySessionId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
