# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_admins_create_user_profile import RequestAdminsCreateUserProfile

class TestRequestAdminsCreateUserProfile(unittest.TestCase):
    """RequestAdminsCreateUserProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestAdminsCreateUserProfile:
        """Test RequestAdminsCreateUserProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestAdminsCreateUserProfile`
        """
        model = RequestAdminsCreateUserProfile()
        if include_optional:
            return RequestAdminsCreateUserProfile(
                args = convex_client.models.request_admins_create_user_profile_args.Request_admins_createUserProfile_args(
                    minutes_remaining = 1.337, 
                    next_billing_date = 1.337, 
                    role = null, 
                    subscription = null, )
            )
        else:
            return RequestAdminsCreateUserProfile(
                args = convex_client.models.request_admins_create_user_profile_args.Request_admins_createUserProfile_args(
                    minutes_remaining = 1.337, 
                    next_billing_date = 1.337, 
                    role = null, 
                    subscription = null, ),
        )
        """

    def testRequestAdminsCreateUserProfile(self):
        """Test RequestAdminsCreateUserProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
