# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_invite_codes_create_default_user_profile_args import RequestInviteCodesCreateDefaultUserProfileArgs

class TestRequestInviteCodesCreateDefaultUserProfileArgs(unittest.TestCase):
    """RequestInviteCodesCreateDefaultUserProfileArgs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestInviteCodesCreateDefaultUserProfileArgs:
        """Test RequestInviteCodesCreateDefaultUserProfileArgs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestInviteCodesCreateDefaultUserProfileArgs`
        """
        model = RequestInviteCodesCreateDefaultUserProfileArgs()
        if include_optional:
            return RequestInviteCodesCreateDefaultUserProfileArgs(
                email = ''
            )
        else:
            return RequestInviteCodesCreateDefaultUserProfileArgs(
                email = '',
        )
        """

    def testRequestInviteCodesCreateDefaultUserProfileArgs(self):
        """Test RequestInviteCodesCreateDefaultUserProfileArgs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
