# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_code_session_states_get_value_terminal import ResponseCodeSessionStatesGetValueTerminal

class TestResponseCodeSessionStatesGetValueTerminal(unittest.TestCase):
    """ResponseCodeSessionStatesGetValueTerminal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseCodeSessionStatesGetValueTerminal:
        """Test ResponseCodeSessionStatesGetValueTerminal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseCodeSessionStatesGetValueTerminal`
        """
        model = ResponseCodeSessionStatesGetValueTerminal()
        if include_optional:
            return ResponseCodeSessionStatesGetValueTerminal(
                execution_time = 1.337,
                is_error = True,
                output = ''
            )
        else:
            return ResponseCodeSessionStatesGetValueTerminal(
                is_error = True,
                output = '',
        )
        """

    def testResponseCodeSessionStatesGetValueTerminal(self):
        """Test ResponseCodeSessionStatesGetValueTerminal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
