# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_user_profiles_update_subscription_by_email_internal_args import RequestUserProfilesUpdateSubscriptionByEmailInternalArgs

class TestRequestUserProfilesUpdateSubscriptionByEmailInternalArgs(unittest.TestCase):
    """RequestUserProfilesUpdateSubscriptionByEmailInternalArgs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestUserProfilesUpdateSubscriptionByEmailInternalArgs:
        """Test RequestUserProfilesUpdateSubscriptionByEmailInternalArgs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestUserProfilesUpdateSubscriptionByEmailInternalArgs`
        """
        model = RequestUserProfilesUpdateSubscriptionByEmailInternalArgs()
        if include_optional:
            return RequestUserProfilesUpdateSubscriptionByEmailInternalArgs(
                current_period_end = 1.337,
                current_period_start = 1.337,
                email = '',
                evaluation_count = 1.337,
                interval = None,
                latest_subscription_id = '',
                minutes_remaining = 1.337,
                plan_name = None,
                refresh_date = 1.337,
                subscription_status = ''
            )
        else:
            return RequestUserProfilesUpdateSubscriptionByEmailInternalArgs(
                email = '',
        )
        """

    def testRequestUserProfilesUpdateSubscriptionByEmailInternalArgs(self):
        """Test RequestUserProfilesUpdateSubscriptionByEmailInternalArgs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
