# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_code_runner_run_code_args import RequestCodeRunnerRunCodeArgs

class TestRequestCodeRunnerRunCodeArgs(unittest.TestCase):
    """RequestCodeRunnerRunCodeArgs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestCodeRunnerRunCodeArgs:
        """Test RequestCodeRunnerRunCodeArgs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestCodeRunnerRunCodeArgs`
        """
        model = RequestCodeRunnerRunCodeArgs()
        if include_optional:
            return RequestCodeRunnerRunCodeArgs(
                code = '',
                language = '',
                question_id = ''
            )
        else:
            return RequestCodeRunnerRunCodeArgs(
                code = '',
                language = '',
                question_id = '',
        )
        """

    def testRequestCodeRunnerRunCodeArgs(self):
        """Test RequestCodeRunnerRunCodeArgs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
