# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_pricings_get_pricing import ResponsePricingsGetPricing

class TestResponsePricingsGetPricing(unittest.TestCase):
    """ResponsePricingsGetPricing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponsePricingsGetPricing:
        """Test ResponsePricingsGetPricing
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponsePricingsGetPricing`
        """
        model = ResponsePricingsGetPricing()
        if include_optional:
            return ResponsePricingsGetPricing(
                status = 'success',
                error_message = '',
                error_data = None,
                value = None
            )
        else:
            return ResponsePricingsGetPricing(
                status = 'success',
        )
        """

    def testResponsePricingsGetPricing(self):
        """Test ResponsePricingsGetPricing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
