# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_actions_run_ground_truth_test import ResponseActionsRunGroundTruthTest

class TestResponseActionsRunGroundTruthTest(unittest.TestCase):
    """ResponseActionsRunGroundTruthTest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseActionsRunGroundTruthTest:
        """Test ResponseActionsRunGroundTruthTest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseActionsRunGroundTruthTest`
        """
        model = ResponseActionsRunGroundTruthTest()
        if include_optional:
            return ResponseActionsRunGroundTruthTest(
                status = 'success',
                error_message = '',
                error_data = None,
                value = [
                    convex_client.models.response_actions_run_ground_truth_test_value_inner.Response_actions_runGroundTruthTest_value_inner(
                        actual = null, 
                        case_number = 1.337, 
                        error = '', 
                        expected = null, 
                        input = convex_client.models.input.input(), 
                        passed = True, 
                        stdout = '', )
                    ]
            )
        else:
            return ResponseActionsRunGroundTruthTest(
                status = 'success',
        )
        """

    def testResponseActionsRunGroundTruthTest(self):
        """Test ResponseActionsRunGroundTruthTest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
