# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_actions_get_session_metadata_value import ResponseActionsGetSessionMetadataValue

class TestResponseActionsGetSessionMetadataValue(unittest.TestCase):
    """ResponseActionsGetSessionMetadataValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseActionsGetSessionMetadataValue:
        """Test ResponseActionsGetSessionMetadataValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseActionsGetSessionMetadataValue`
        """
        model = ResponseActionsGetSessionMetadataValue()
        if include_optional:
            return ResponseActionsGetSessionMetadataValue(
                agent_thread_id = '',
                assistant_id = '',
                question_content = '',
                question_title = '',
                session_id = '',
                session_status = ''
            )
        else:
            return ResponseActionsGetSessionMetadataValue(
                agent_thread_id = '',
                assistant_id = '',
                question_content = '',
                question_title = '',
                session_id = '',
                session_status = '',
        )
        """

    def testResponseActionsGetSessionMetadataValue(self):
        """Test ResponseActionsGetSessionMetadataValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
