# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_agent_states_set_by_session_id_args import RequestAgentStatesSetBySessionIdArgs

class TestRequestAgentStatesSetBySessionIdArgs(unittest.TestCase):
    """RequestAgentStatesSetBySessionIdArgs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestAgentStatesSetBySessionIdArgs:
        """Test RequestAgentStatesSetBySessionIdArgs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestAgentStatesSetBySessionIdArgs`
        """
        model = RequestAgentStatesSetBySessionIdArgs()
        if include_optional:
            return RequestAgentStatesSetBySessionIdArgs(
                session_id = '',
                state = None
            )
        else:
            return RequestAgentStatesSetBySessionIdArgs(
                session_id = '',
                state = None,
        )
        """

    def testRequestAgentStatesSetBySessionIdArgs(self):
        """Test RequestAgentStatesSetBySessionIdArgs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
