# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_sessions_create_code_session import RequestSessionsCreateCodeSession

class TestRequestSessionsCreateCodeSession(unittest.TestCase):
    """RequestSessionsCreateCodeSession unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestSessionsCreateCodeSession:
        """Test RequestSessionsCreateCodeSession
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestSessionsCreateCodeSession`
        """
        model = RequestSessionsCreateCodeSession()
        if include_optional:
            return RequestSessionsCreateCodeSession(
                args = convex_client.models.request_sessions_create_code_session_args.Request_sessions_createCodeSession_args(
                    agent_thread_id = '', 
                    assistant_id = '', 
                    interview_flow = [
                        ''
                        ], 
                    interview_mode = null, 
                    interview_type = null, 
                    model_name = '', 
                    programming_language = '', 
                    question_id = '', 
                    time_limit = 1.337, 
                    voice = '', )
            )
        else:
            return RequestSessionsCreateCodeSession(
                args = convex_client.models.request_sessions_create_code_session_args.Request_sessions_createCodeSession_args(
                    agent_thread_id = '', 
                    assistant_id = '', 
                    interview_flow = [
                        ''
                        ], 
                    interview_mode = null, 
                    interview_type = null, 
                    model_name = '', 
                    programming_language = '', 
                    question_id = '', 
                    time_limit = 1.337, 
                    voice = '', ),
        )
        """

    def testRequestSessionsCreateCodeSession(self):
        """Test RequestSessionsCreateCodeSession"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
