# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.request_user_profiles_get_by_email_internal import RequestUserProfilesGetByEmailInternal

class TestRequestUserProfilesGetByEmailInternal(unittest.TestCase):
    """RequestUserProfilesGetByEmailInternal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RequestUserProfilesGetByEmailInternal:
        """Test RequestUserProfilesGetByEmailInternal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RequestUserProfilesGetByEmailInternal`
        """
        model = RequestUserProfilesGetByEmailInternal()
        if include_optional:
            return RequestUserProfilesGetByEmailInternal(
                args = convex_client.models.request_user_profiles_get_by_email_internal_args.Request_userProfiles_getByEmailInternal_args(
                    email = '', )
            )
        else:
            return RequestUserProfilesGetByEmailInternal(
                args = convex_client.models.request_user_profiles_get_by_email_internal_args.Request_userProfiles_getByEmailInternal_args(
                    email = '', ),
        )
        """

    def testRequestUserProfilesGetByEmailInternal(self):
        """Test RequestUserProfilesGetByEmailInternal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
