# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from convex_client.models.response_sessions_get_session_metrics_internal import ResponseSessionsGetSessionMetricsInternal

class TestResponseSessionsGetSessionMetricsInternal(unittest.TestCase):
    """ResponseSessionsGetSessionMetricsInternal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseSessionsGetSessionMetricsInternal:
        """Test ResponseSessionsGetSessionMetricsInternal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseSessionsGetSessionMetricsInternal`
        """
        model = ResponseSessionsGetSessionMetricsInternal()
        if include_optional:
            return ResponseSessionsGetSessionMetricsInternal(
                status = 'success',
                error_message = '',
                error_data = None,
                value = convex_client.models.response_sessions_get_session_metrics_internal_value.Response_sessions_getSessionMetricsInternal_value(
                    completed = convex_client.models.response_sessions_get_session_metrics_internal_value_completed.Response_sessions_getSessionMetricsInternal_value_completed(
                        eval_pending = 1.337, 
                        eval_ready = 1.337, 
                        total = 1.337, ), 
                    in_progress = convex_client.models.response_sessions_get_session_metrics_internal_value_completed.Response_sessions_getSessionMetricsInternal_value_completed(
                        eval_pending = 1.337, 
                        eval_ready = 1.337, 
                        total = 1.337, ), 
                    not_started = , )
            )
        else:
            return ResponseSessionsGetSessionMetricsInternal(
                status = 'success',
        )
        """

    def testResponseSessionsGetSessionMetricsInternal(self):
        """Test ResponseSessionsGetSessionMetricsInternal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
