# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of5_data_after_inner import RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5DataAfterInner
from typing import Optional, Set
from typing_extensions import Self

class RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5Data(BaseModel):
    """
    RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5Data
    """ # noqa: E501
    after: List[RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5DataAfterInner]
    before: List[RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5DataAfterInner]
    __properties: ClassVar[List[str]] = ["after", "before"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5Data from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in after (list)
        _items = []
        if self.after:
            for _item_after in self.after:
                if _item_after:
                    _items.append(_item_after.to_dict())
            _dict['after'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in before (list)
        _items = []
        if self.before:
            for _item_before in self.before:
                if _item_before:
                    _items.append(_item_before.to_dict())
            _dict['before'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5Data from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "after": [RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5DataAfterInner.from_dict(_item) for _item in obj["after"]] if obj.get("after") is not None else None,
            "before": [RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5DataAfterInner.from_dict(_item) for _item in obj["before"]] if obj.get("before") is not None else None
        })
        return _obj


