# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of import RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf
from convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of1 import RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1
from convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of2 import RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2
from convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of3 import RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3
from convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of4 import RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4
from convex_client.models.request_code_session_events_commit_code_session_event_args_event_one_of5 import RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

REQUESTCODESESSIONEVENTSCOMMITCODESESSIONEVENTARGSEVENT_ONE_OF_SCHEMAS = ["RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf", "RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1", "RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2", "RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3", "RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4", "RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5"]

class RequestCodeSessionEventsCommitCodeSessionEventArgsEvent(BaseModel):
    """
    RequestCodeSessionEventsCommitCodeSessionEventArgsEvent
    """
    # data type: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf
    oneof_schema_1_validator: Optional[RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf] = None
    # data type: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1
    oneof_schema_2_validator: Optional[RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1] = None
    # data type: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2
    oneof_schema_3_validator: Optional[RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2] = None
    # data type: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3
    oneof_schema_4_validator: Optional[RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3] = None
    # data type: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4
    oneof_schema_5_validator: Optional[RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4] = None
    # data type: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5
    oneof_schema_6_validator: Optional[RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5] = None
    # data type: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2
    oneof_schema_7_validator: Optional[RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2] = None
    actual_instance: Optional[Union[RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5]] = None
    one_of_schemas: Set[str] = { "RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf", "RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1", "RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2", "RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3", "RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4", "RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = RequestCodeSessionEventsCommitCodeSessionEventArgsEvent.model_construct()
        error_messages = []
        match = 0
        # validate data type: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf
        if not isinstance(v, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf`")
        else:
            match += 1
        # validate data type: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1
        if not isinstance(v, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1`")
        else:
            match += 1
        # validate data type: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2
        if not isinstance(v, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2`")
        else:
            match += 1
        # validate data type: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3
        if not isinstance(v, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3`")
        else:
            match += 1
        # validate data type: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4
        if not isinstance(v, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4`")
        else:
            match += 1
        # validate data type: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5
        if not isinstance(v, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5`")
        else:
            match += 1
        # validate data type: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2
        if not isinstance(v, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in RequestCodeSessionEventsCommitCodeSessionEventArgsEvent with oneOf schemas: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in RequestCodeSessionEventsCommitCodeSessionEventArgsEvent with oneOf schemas: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf
        try:
            instance.actual_instance = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1
        try:
            instance.actual_instance = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2
        try:
            instance.actual_instance = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3
        try:
            instance.actual_instance = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4
        try:
            instance.actual_instance = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5
        try:
            instance.actual_instance = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2
        try:
            instance.actual_instance = RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into RequestCodeSessionEventsCommitCodeSessionEventArgsEvent with oneOf schemas: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into RequestCodeSessionEventsCommitCodeSessionEventArgsEvent with oneOf schemas: RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf1, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf2, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf3, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf4, RequestCodeSessionEventsCommitCodeSessionEventArgsEventOneOf5]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


