# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from convex_client.models.request_jobs_create_args_status import RequestJobsCreateArgsStatus
from typing import Optional, Set
from typing_extensions import Self

class RequestJobsCreateArgs(BaseModel):
    """
    RequestJobsCreateArgs
    """ # noqa: E501
    last_update: Union[StrictFloat, StrictInt] = Field(alias="lastUpdate")
    num_retries: Union[StrictFloat, StrictInt] = Field(alias="numRetries")
    session_id: StrictStr = Field(description="ID from table \"sessions\"", alias="sessionId")
    status: RequestJobsCreateArgsStatus
    __properties: ClassVar[List[str]] = ["lastUpdate", "numRetries", "sessionId", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RequestJobsCreateArgs from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict['status'] = self.status.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RequestJobsCreateArgs from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lastUpdate": obj.get("lastUpdate"),
            "numRetries": obj.get("numRetries"),
            "sessionId": obj.get("sessionId"),
            "status": RequestJobsCreateArgsStatus.from_dict(obj["status"]) if obj.get("status") is not None else None
        })
        return _obj


