# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ResponseActionsRunGroundTruthTestValueInner(BaseModel):
    """
    ResponseActionsRunGroundTruthTestValueInner
    """ # noqa: E501
    actual: Optional[Any]
    case_number: Union[StrictFloat, StrictInt] = Field(alias="caseNumber")
    error: Optional[StrictStr]
    expected: Optional[Any]
    input: Dict[str, Any]
    passed: StrictBool
    stdout: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["actual", "caseNumber", "error", "expected", "input", "passed", "stdout"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResponseActionsRunGroundTruthTestValueInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if actual (nullable) is None
        # and model_fields_set contains the field
        if self.actual is None and "actual" in self.model_fields_set:
            _dict['actual'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if expected (nullable) is None
        # and model_fields_set contains the field
        if self.expected is None and "expected" in self.model_fields_set:
            _dict['expected'] = None

        # set to None if stdout (nullable) is None
        # and model_fields_set contains the field
        if self.stdout is None and "stdout" in self.model_fields_set:
            _dict['stdout'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResponseActionsRunGroundTruthTestValueInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "actual": obj.get("actual"),
            "caseNumber": obj.get("caseNumber"),
            "error": obj.get("error"),
            "expected": obj.get("expected"),
            "input": obj.get("input"),
            "passed": obj.get("passed"),
            "stdout": obj.get("stdout")
        })
        return _obj


