# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from convex_client.models.response_sessions_get_session_metrics_internal_value_completed import ResponseSessionsGetSessionMetricsInternalValueCompleted
from typing import Optional, Set
from typing_extensions import Self

class ResponseSessionsGetSessionMetricsInternalValue(BaseModel):
    """
    ResponseSessionsGetSessionMetricsInternalValue
    """ # noqa: E501
    completed: ResponseSessionsGetSessionMetricsInternalValueCompleted
    in_progress: ResponseSessionsGetSessionMetricsInternalValueCompleted = Field(alias="inProgress")
    not_started: ResponseSessionsGetSessionMetricsInternalValueCompleted = Field(alias="notStarted")
    __properties: ClassVar[List[str]] = ["completed", "inProgress", "notStarted"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResponseSessionsGetSessionMetricsInternalValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of completed
        if self.completed:
            _dict['completed'] = self.completed.to_dict()
        # override the default output from pydantic by calling `to_dict()` of in_progress
        if self.in_progress:
            _dict['inProgress'] = self.in_progress.to_dict()
        # override the default output from pydantic by calling `to_dict()` of not_started
        if self.not_started:
            _dict['notStarted'] = self.not_started.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResponseSessionsGetSessionMetricsInternalValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "completed": ResponseSessionsGetSessionMetricsInternalValueCompleted.from_dict(obj["completed"]) if obj.get("completed") is not None else None,
            "inProgress": ResponseSessionsGetSessionMetricsInternalValueCompleted.from_dict(obj["inProgress"]) if obj.get("inProgress") is not None else None,
            "notStarted": ResponseSessionsGetSessionMetricsInternalValueCompleted.from_dict(obj["notStarted"]) if obj.get("notStarted") is not None else None
        })
        return _obj


