# coding: utf-8

"""
    Convex App - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from convex_client.models.response_actions_run_ground_truth_test_value_inner import ResponseActionsRunGroundTruthTestValueInner
from typing import Optional, Set
from typing_extensions import Self

class ResponseActionsRunTestsValue(BaseModel):
    """
    ResponseActionsRunTestsValue
    """ # noqa: E501
    exception: Optional[StrictStr] = None
    execution_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="executionTime")
    is_error: StrictBool = Field(alias="isError")
    status: StrictStr
    stderr: Optional[StrictStr] = None
    stdout: Optional[StrictStr] = None
    test_results: Optional[List[ResponseActionsRunGroundTruthTestValueInner]] = Field(default=None, alias="testResults")
    __properties: ClassVar[List[str]] = ["exception", "executionTime", "isError", "status", "stderr", "stdout", "testResults"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResponseActionsRunTestsValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in test_results (list)
        _items = []
        if self.test_results:
            for _item_test_results in self.test_results:
                if _item_test_results:
                    _items.append(_item_test_results.to_dict())
            _dict['testResults'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResponseActionsRunTestsValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "exception": obj.get("exception"),
            "executionTime": obj.get("executionTime"),
            "isError": obj.get("isError"),
            "status": obj.get("status"),
            "stderr": obj.get("stderr"),
            "stdout": obj.get("stdout"),
            "testResults": [ResponseActionsRunGroundTruthTestValueInner.from_dict(_item) for _item in obj["testResults"]] if obj.get("testResults") is not None else None
        })
        return _obj


